CREATE ROLE <USER> LOGIN PASSWORD <PASS> NOSUPERUSER;
GRANT CONNECT ON DATABASE <DB> TO <USER>;
GRANT USAGE ON SCHEMA public TO <USER>;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO <USER>;
