CREATE ROLE app_user LOGIN PASSWORD 'ChatBotPDF' NOSUPERUSER;
GRANT CONNECT ON DATABASE ragdb TO app_user;
GRANT USAGE ON SCHEMA public TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
